"""File-manager integration: "Ask Maze AI" in the right-click menu.

Right-click a file in Dolphin (or Nautilus, Nemo, Thunar) and hand it to the
assistant — summarise this PDF, what is in this folder, read the text in this
screenshot. Every desktop stores these menus differently, so each one gets its
own installer here; all of them ultimately run ``maze-ai --file <paths>``.

Everything is written under the user's own data directories, and
:func:`uninstall` removes exactly what :func:`install` created.
"""

from __future__ import annotations

import logging
import os
import shutil
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

from .i18n import tr

log = logging.getLogger(__name__)

_DATA_HOME = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
_CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))

#: Marks every file we create, so uninstall never touches a hand-written one.
MARKER = "X-Maze-AI-Generated=true"


@dataclass
class Integration:
    """One file manager we can add a menu entry to."""

    key: str
    name: str
    binary: str
    path: Path

    @property
    def available(self) -> bool:
        return bool(shutil.which(self.binary))

    @property
    def installed(self) -> bool:
        return self.path.exists()


def _dolphin_menu() -> str:
    """A KDE service menu, in the format KIO has wanted since Frameworks 5.85.

    The old ``Type=Service`` + ``ServiceTypes=KonqPopupMenu/Plugin`` shape is
    deprecated; Plasma 6 reads plain application entries with ``MimeType`` and
    ``Actions`` from ``kio/servicemenus``. ``all/all`` is KIO's pseudo type for
    "anything, folders included".
    """
    return f"""\
[Desktop Entry]
Type=Application
Name={tr("Maze AI")}
Icon=maze-ai
MimeType=all/all;
Actions=mazeask;mazeexplain;
X-KDE-Submenu={tr("Maze AI")}
Exec=maze-ai --file %F
NoDisplay=true
{MARKER}

[Desktop Action mazeask]
Name={tr("Ask about this")}
Icon=maze-ai
Exec=maze-ai --file %F

[Desktop Action mazeexplain]
Name={tr("Explain this")}
Icon=maze-ai
Exec=maze-ai --file-action explain --file %F
"""


def _nautilus_script() -> str:
    """GNOME Files runs plain scripts, passing the selection in the environment."""
    return """\
#!/usr/bin/env bash
# Generated by Maze AI — safe to delete.
# X-Maze-AI-Generated=true
IFS=$'\\n'
paths=()
while read -r line; do
    [ -n "$line" ] && paths+=("$line")
done <<< "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS:-}"
if [ ${#paths[@]} -eq 0 ]; then
    exec maze-ai --ask
fi
exec maze-ai --file "${paths[@]}"
"""


def _nemo_action() -> str:
    return f"""\
[Nemo Action]
Name={tr("Ask Maze AI about this")}
Comment={tr("Hand the selected files to Maze AI")}
Exec=maze-ai --file %F
Icon-Name=maze-ai
Selection=any
Extensions=any;
{MARKER}
"""


_THUNAR_ACTION = {
    "icon": "maze-ai",
    "name": "Ask Maze AI about this",
    "command": "maze-ai --file %F",
    "description": "Hand the selected files to Maze AI",
    "patterns": "*",
}


def integrations() -> list[Integration]:
    """Every file manager we know how to extend, whether installed or not."""
    return [
        Integration(
            "dolphin", "Dolphin (KDE)", "dolphin",
            _DATA_HOME / "kio" / "servicemenus" / "maze-ai.desktop",
        ),
        Integration(
            "nautilus", "Files (GNOME)", "nautilus",
            _DATA_HOME / "nautilus" / "scripts" / tr("Ask Maze AI"),
        ),
        Integration(
            "nemo", "Nemo (Cinnamon)", "nemo",
            _DATA_HOME / "nemo" / "actions" / "maze-ai.nemo_action",
        ),
        Integration(
            "thunar", "Thunar (XFCE)", "thunar",
            _CONFIG_HOME / "Thunar" / "uca.xml",
        ),
    ]


def available() -> list[Integration]:
    """The file managers actually installed on this machine."""
    return [item for item in integrations() if item.available]


# ── Thunar needs surgery on a shared XML file ────────────────────────────
def _thunar_install(path: Path) -> None:
    """Add our action to Thunar's custom-actions file, keeping the others."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        try:
            tree = ET.parse(path)
            root = tree.getroot()
        except ET.ParseError:
            root = ET.Element("actions")
            tree = ET.ElementTree(root)
    else:
        root = ET.Element("actions")
        tree = ET.ElementTree(root)

    for action in root.findall("action"):
        command = action.findtext("command") or ""
        if "maze-ai" in command:
            return  # already there
    action = ET.SubElement(root, "action")
    for tag, value in (
        ("icon", _THUNAR_ACTION["icon"]),
        ("name", tr(_THUNAR_ACTION["name"])),
        ("unique-id", "maze-ai-1"),
        ("command", _THUNAR_ACTION["command"]),
        ("description", tr(_THUNAR_ACTION["description"])),
        ("patterns", _THUNAR_ACTION["patterns"]),
    ):
        ET.SubElement(action, tag).text = value
    for flag in ("directories", "audio-files", "image-files", "other-files",
                 "text-files", "video-files"):
        ET.SubElement(action, flag)
    tree.write(path, encoding="UTF-8", xml_declaration=True)


def _thunar_uninstall(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        tree = ET.parse(path)
    except ET.ParseError:
        return False
    root = tree.getroot()
    removed = False
    for action in list(root.findall("action")):
        if "maze-ai" in (action.findtext("command") or ""):
            root.remove(action)
            removed = True
    if removed:
        tree.write(path, encoding="UTF-8", xml_declaration=True)
    return removed


# ── install / uninstall ──────────────────────────────────────────────────
def install(keys: list[str] | None = None) -> dict[str, str]:
    """Add the menu entry to the given (or all available) file managers.

    Returns ``{key: ""}`` on success or ``{key: "error message"}`` on failure.
    """
    results: dict[str, str] = {}
    for item in integrations():
        if keys is not None and item.key not in keys:
            continue
        if keys is None and not item.available:
            continue
        try:
            if item.key == "thunar":
                _thunar_install(item.path)
            else:
                item.path.parent.mkdir(parents=True, exist_ok=True)
                body = {
                    "dolphin": _dolphin_menu,
                    "nautilus": _nautilus_script,
                    "nemo": _nemo_action,
                }[item.key]()
                item.path.write_text(body, encoding="utf-8")
                if item.key in ("dolphin", "nautilus"):
                    # KDE ≥ 5.100 and Nautilus both require the executable bit.
                    item.path.chmod(0o755)
            results[item.key] = ""
            log.info("installed %s integration at %s", item.key, item.path)
        except OSError as exc:
            results[item.key] = str(exc)
            log.warning("could not install %s integration: %s", item.key, exc)
    return results


def uninstall(keys: list[str] | None = None) -> list[str]:
    """Remove what :func:`install` created. Returns the keys actually removed."""
    removed: list[str] = []
    for item in integrations():
        if keys is not None and item.key not in keys:
            continue
        try:
            if item.key == "thunar":
                if _thunar_uninstall(item.path):
                    removed.append(item.key)
                continue
            if item.path.exists():
                item.path.unlink()
                removed.append(item.key)
        except OSError as exc:
            log.warning("could not remove %s integration: %s", item.key, exc)
    return removed


def status() -> dict[str, bool]:
    """Which integrations are currently in place."""
    result = {}
    for item in integrations():
        if item.key == "thunar":
            text = item.path.read_text(encoding="utf-8", errors="replace") \
                if item.path.exists() else ""
            result[item.key] = "maze-ai" in text
        else:
            result[item.key] = item.installed
    return result


def describe() -> str:
    """One line for the UI: what is installed, what could be."""
    found = available()
    if not found:
        return tr("No supported file manager found.")
    state = status()
    parts = []
    for item in found:
        mark = "✓" if state.get(item.key) else "—"
        parts.append(f"{mark} {item.name}")
    return "  ·  ".join(parts)
